version: "3.8"
services:
  kong:
    image: kong:latest
    container_name: kong-container
    restart: always
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    environment:
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
  springboot-app:
    image: dhruthikonijeti/springboot
    container_name: springboot-container
    restart: always
    ports:
      - 8080:8080